INSERT INTO STUDENT(ID,NAME,ADDRESS) VALUES(101,'Warsha Rathod','Pune');

INSERT INTO STUDENT(ID,NAME,ADDRESS) VALUES(102,'Radhika Pawar','Mumbai');

INSERT INTO STUDENT(ID,NAME,ADDRESS) VALUES(103,'Kiran Kumar','Dellhi');

INSERT INTO STUDENT(ID,NAME,ADDRESS) VALUES(104,'Sweta Kumari','Bihar');